WIFI_SSID = "LPWAN-IoT-XY"
WIFI_PWD  = "LPWAN-IoT-XY-WiFi"

_MQTT_REMOTE_SERVER_IP_ = "147.229.148.105"
_MQTT_REMOTE_SERVER_PORT_ = 1883

_MQTT_CLIENT_ID_ = "Your Client ID"
_MQTT_ACCESS_TOKEN_ = "Your Access Token"
_MQTT_PASSWORD_ = ""

_COAP_REMOTE_SERVER_IP_ = "147.229.148.105"
_COAP_REMOTE_SERVER_PORT_ = 5683


_COAP_CLIENT_ID_ = "Your Client ID"
_COAP_ACCESS_TOKEN_ = "Your Access Token"
_COAP_PASSWORD_ = ""